:toc: left
:sectnums:

= alignment

alignment is a library to align strings.
The procedures consider multibyte strings (ex: あいうえお, 漢字).

== ライブラリ説明

テキストを単純に `strutils.align` などでパディングした場合、
ターミナルで確認した際に、揃い位置がずれることがある。
これは半角アルファベットとひらがななどを含むマルチバイト文字で、
文字のバイトサイズが異なることに起因する。

以下の例を確認しよう。

この例では、"a"の長さが1、"あ"の長さが3であることがわかる。
`len` プロシージャは文字の数ではなく、文字のバイト長であるを返す。

同様に、 `strutils.alignLeft` も文字列のパディングをバイト長を基準に行う。
よって、シングルバイト文字のみのテキストとマルチバイト文字を含む文字列に対して
alignを行った場合、以下のような結果になる。

見ての通り、バイト長に関しては両者とも一致するものの、文字列の見た目上のパディン
グについては不揃いになってします。これらはWebブラウザのレンダリングの関係で
不揃いであることがわかりにくくなっているものの、これの検証を
ターミナル上で実施し、ターミナル上で等幅フォントを使用して確認したとき、
それは顕著にわかるだろう。

本ライブラリでは、このTUI上で確認したときの位置揃えの不一致の問題を解消すること
を目的とする。

[source,nim]
----
import strutils

doAssert "a".len == 1
doAssert "あ".len == 3
doAssert "a".alignLeft(5) == "a    "
doAssert "あ".alignLeft(5) == "あ  "
doAssert "a".alignLeft(5).len == 5
doAssert "あ".alignLeft(5).len == 5
----

== Development

nim -v

  Nim Compiler Version 0.19.6 [Linux: amd64]
  Compiled at 2019-05-10
  Copyright (c) 2006-2018 by Andreas Rumpf

  git hash: c6f601d48ec81e0d6e052ba0d19a195b55cc68f2
  active boot switches: -d:release

nimble -v

  nimble v0.9.0 compiled at 2018-10-27 18:10:03
  git hash: couldn't determine git hash


== Usage

[source,nim]
----
import alignment

let s = @["abcde", "あいうえお", "ABC", "あ", "123456789"]
let aligned = s.alignCenter
doAssert aligned[0] == "  abcde   "
doAssert aligned[1] == "あいうえお"
doAssert aligned[2] == "   ABC    "
doAssert aligned[3] == "    あ    "
doAssert aligned[4] == "123456789 "

for line in aligned:
  echo "| ", line, " |"

## Output:
## |   abcde    |
## | あいうえお |
## |    ABC     |
## |     あ     |
## | 123456789  |
----

== Install

[source,bash]
nimble install alignment

== License

MIT

== Document

* https://jiro4989.github.io/alignment/alignment.html
